application: kantorreddit
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: view/stylesheets
  
- url: /favicon.ico
  static_dir: view/stylesheets
  
- url: /.*
  script: view.reddit.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: webob
  version: latest
